version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: projectDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  nestjs-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: projectDB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
volumes:
  postgres-data:
